# Generated by Django 4.2 on 2023-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='written',
            old_name='text',
            new_name='transcript',
        ),
        migrations.AddField(
            model_name='written',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='written',
            name='word_timings',
            field=models.TextField(null=True),
        ),
    ]
